### ISSUE TITLE
Agregar opcion de ayuda en el menu

### ISSUE THREAD

**Issue by lmarcelle01** [eTutorTeam/eTutor.BackEnd#23]
Agregar una opción de ayuda en el menu principal del app, la cual debe dirigir al usuario a la pagina de ayuda en linea.

**Comment by juandozuna** [comment]
Necesito saber cual es la URL del servicio de ayuda para ponerlo a apuntar a ese sitio

**Comment by juandozuna** [comment]
@mrmiguetara @lmarcelle01

**Comment by lmarcelle01** [comment]
https://etutor-helpapp.firebaseapp.com/welcome
