### ISSUE TITLE
no se puede seleccionar "prefiero no especificar" como genero en el registro

### ISSUE THREAD

**Issue by lmarcelle01** [eTutorTeam/eTutor.BackEnd#26]
Eliminar opción “prefiero no especificar” en los Géneros de la pagina de registro. al intentar seleccionar esa opcion y enviar el formulario, se genera un error

**Comment by juandozuna** [comment]
La opción fue eliminada, en si, no es necesario poner esa opción, porque solo hay hombre y mujeres, el que no lo quiera así que se cuide
