### ISSUE TITLE
No se cancela tutoria cuando el tutor intenta cancelarla sin que esta se haya iniciado

### ISSUE THREAD

**Issue by lmarcelle01** [eTutorTeam/eTutor.BackEnd#31]
No se puede cancelar tutoria cuando el tutor intenta hacerlo desde el detalle de la tutoria, en lugar de iniciarla

**Comment by lmarcelle01** [comment]
tampoco funciona con el estudianre si se intenta cancelar sin haberla iniciado

**Comment by juandozuna** [comment]
El problema fue resuelto, el tema era que el request en el servidor es PATCH y se le estaba mandando un PUT desde el APP, estaba explotando y no salia el error en la aplicación
